### ISSUE TITLE
Can I fork/change this license?

### ISSUE THREAD

**Issue by makkus** [licensezero/licensezero-private-license#3]
Hi @kemitchell,

quick question, this is loosely related to https://github.com/licensezero/parity-public-license/issues/23:

As this repo doesn't have any license information itself, am I allowed to fork this (happy to do it under a different name), change the license text (I want to remove the sublicensing-part), and use it as the 'commercial' license for my dual-licensed project(s)?

Cheers!

**Comment by kemitchell** [comment]
@makkus you may do what you like with the text, as long as you change the name.

I have another process starting up to provide forms and other written resources for independent developers dual licensing _without_ L0. If you'd like to know more, drop me a line.

**Comment by makkus** [comment]
Thanks. And yes, I'd be interested.
